//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trololo.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trololo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Begin {
            get {
                object obj = ResourceManager.GetObject("Begin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blockTexture {
            get {
                object obj = ResourceManager.GetObject("blockTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ContinueButton {
            get {
                object obj = ResourceManager.GetObject("ContinueButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeathScreen {
            get {
                object obj = ResourceManager.GetObject("DeathScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Enemy {
            get {
                object obj = ResourceManager.GetObject("Enemy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EnemyGround {
            get {
                object obj = ResourceManager.GetObject("EnemyGround", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream EnemyShoot {
            get {
                return ResourceManager.GetStream("EnemyShoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EnemyShootSprite {
            get {
                object obj = ResourceManager.GetObject("EnemyShootSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enemySky {
            get {
                object obj = ResourceManager.GetObject("enemySky", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gun {
            get {
                object obj = ResourceManager.GetObject("gun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Heal {
            get {
                object obj = ResourceManager.GetObject("Heal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HealthEmpty {
            get {
                object obj = ResourceManager.GetObject("HealthEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HealthFull {
            get {
                object obj = ResourceManager.GetObject("HealthFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InvinsiblePlayer {
            get {
                object obj = ResourceManager.GetObject("InvinsiblePlayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ladder {
            get {
                object obj = ResourceManager.GetObject("Ladder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ......................X
        ///......................X
        ///......................X
        ///......................X
        ///......................X
        ///..........G...........X
        ///......................X
        ///......................X
        ///......................X
        ///......................X
        ///......................X
        ///..P...................X
        ///......................X
        ///......................X
        ///FFFFFFFFFFFFFFFFFFFFFFF
        ///FFFFFFFFFFFFFFFFFFFFFFF
        ///.
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///......................X
        ///......................X
        ///......................X
        ///......................X
        ///......................X
        ///..........G...........X
        ///......................X
        ///......................X
        ///.............S........X
        ///......................X
        ///......................X
        ///..P........FFFFF......X
        ///.........FFFFFFFF.....X
        ///........FFFFFFFFFF....X
        ///FFFFFFFFFFFFFFFFFFFFFFF
        ///FFFFFFFFFFFFFFFFFFFFFFF
        ///.
        /// </summary>
        internal static string level2 {
            get {
                return ResourceManager.GetString("level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ......................X
        ///.E....................X
        ///......................X
        ///......................X
        ///......................X
        ///..........G...........X
        ///......................X
        ///......................X
        ///......................X
        ///......................X
        ///......................X
        ///..P...................X
        ///......................X
        ///......................X
        ///FFFFFFFFFFFFFFFFFFFFFFF
        ///FFFFFFFFFFFFFFFFFFFFFFF
        ///.
        /// </summary>
        internal static string level3 {
            get {
                return ResourceManager.GetString("level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .....................XX
        ///..............E......XX
        ///.....................XX
        ///.....E...............XX
        ///.....................XX
        ///E....................XX
        ///.....................XX
        ///..........G..........XX
        ///.....................XX
        ///.....................XX
        ///.....................XX
        ///..P..................XX
        ///.....................XX
        ///.....................XX
        ///FFFFFFFFFFFFFFFFFFFFFFF
        ///FFFFFFFFFFFFFFFFFFFFFFF
        ///
        ///.
        /// </summary>
        internal static string level4 {
            get {
                return ResourceManager.GetString("level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .....................FF
        ///.....................FF
        ///.....................FF
        ///.....................FF
        ///.....................FF
        ///.....................FF
        ///.................FFFFFF
        ///.....................FF
        ///.....................XX
        ///..P..................XX
        ///.....................XX
        ///..............FFFFFFFFF
        ///..........FFFFFFFFFFFFF
        ///.......FFFFFFFFFFFFFFFF
        ///FFFFFFFFFFFFFFFFFFFFFFF
        ///FFFFFFFFFFFFFFFFFFFFFFF
        ///
        ///.
        /// </summary>
        internal static string level5 {
            get {
                return ResourceManager.GetString("level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FFFFFFFFFFFFFFFFFFFFFFF
        ///................FFFFFFF
        ///......E.............FFF
        ///......................F
        ///......................F
        ///......................F
        ///.P....................F
        ///.............#FFFF....F
        ///.............#..FF....F
        ///.....F..FF...#..FF....X
        ///....FF.......#..FF....X
        ///FFFFFF..........FF....X
        ///FFFFFF..........FF....X
        ///FFFFFF..........FF....X
        ///FFFFFF.........FFFFFFFF
        ///FFF.FFFFFFFFFFFFFFFFFFF
        ///
        ///.
        /// </summary>
        internal static string level6 {
            get {
                return ResourceManager.GetString("level6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ..P..................FX
        ///.....................FF
        ///....................FFF
        ///..................FFFFX
        ///...............FFFFFFFX
        ///FFFFF.........FFFFF...X
        ///.............FF.......X
        ///E...........FF........X
        ///.........FFFF.........X
        ///........FF............X
        ///E.....................X
        ///......................X
        ///E.....................X
        ///......................X
        ///...............FFFFFFFX
        ///FFFFFFFFFFFFFFFFFFFFFFF
        ///
        ///.
        /// </summary>
        internal static string level7 {
            get {
                return ResourceManager.GetString("level7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LevelRestart {
            get {
                object obj = ResourceManager.GetObject("LevelRestart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menu {
            get {
                object obj = ResourceManager.GetObject("menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream mvpSound {
            get {
                return ResourceManager.GetStream("mvpSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PauseBack {
            get {
                object obj = ResourceManager.GetObject("PauseBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PauseMenu {
            get {
                object obj = ResourceManager.GetObject("PauseMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream PlayerShoot {
            get {
                return ResourceManager.GetStream("PlayerShoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerShootSprite {
            get {
                object obj = ResourceManager.GetObject("PlayerShootSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RotatedInvinsiblePlayer {
            get {
                object obj = ResourceManager.GetObject("RotatedInvinsiblePlayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap testPlayer {
            get {
                object obj = ResourceManager.GetObject("testPlayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap testPlayerRotated {
            get {
                object obj = ResourceManager.GetObject("testPlayerRotated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ToMenuButton {
            get {
                object obj = ResourceManager.GetObject("ToMenuButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
